name: Terraform Destroy

on:
  workflow_dispatch:  # Esto permite ejecutar el workflow manualmente desde GitHub

jobs:
  destroy:
    runs-on: ubuntu-latest
    name: Destroy Infra

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.5.7

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Generate terraform.tfvars file
        run: |
          echo "aws_region = \"${{ secrets.TF_aws_region }}\"" > terraform.tfvars
          echo "project_name = \"${{ secrets.TF_project_name }}\"" >> terraform.tfvars
          echo "environment = \"${{ secrets.TF_environment }}\"" >> terraform.tfvars
          echo "cloudfront_price_class = \"${{ secrets.TF_cloudfront_price_class }}\"" >> terraform.tfvars

      - name: Terraform Init
        run: terraform init

      - name: Terraform Destroy
        run: terraform destroy -auto-approve
