name: Terraform Deploy

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  terraform:
    name: 'Terraform CI'
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: 1.5.7

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v3
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Generate terraform.tfvars file
      run: |
        echo "aws_region = \"${{ secrets.TF_aws_region }}\"" > terraform.tfvars
        echo "project_name = \"${{ secrets.TF_project_name }}\"" >> terraform.tfvars
        echo "environment = \"${{ secrets.TF_environment }}\"" >> terraform.tfvars
        echo "cloudfront_price_class = \"${{ secrets.TF_cloudfront_price_class }}\"" >> terraform.tfvars

    - name: Cleanup previous backend config
      run: rm -rf .terraform

    - name: Terraform Init
      run: terraform init

    - name: Terraform Plan
      run: terraform plan

    # Solo aplicar si es push (no pull_request)
    - name: Terraform Apply
      run: terraform apply -auto-approve
